In [39]:
import numpy as np
import pandas as pd

In [83]:
train_labeled_df = pd.read_csv(
    './dataanalysis-final/train_labeled_classification.csv')
train_unlabeled_df = pd.read_csv(
    './dataanalysis-final/train_unlabeled_classification.csv')
test_df = pd.read_csv(
    './dataanalysis-final/test_classification.csv')

In [86]:
train_labeled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 55 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature00  600 non-null    float64
 1   feature01  600 non-null    float64
 2   feature02  600 non-null    float64
 3   feature03  600 non-null    float64
 4   feature04  600 non-null    float64
 5   feature05  600 non-null    float64
 6   feature06  600 non-null    float64
 7   feature07  600 non-null    float64
 8   feature08  600 non-null    float64
 9   feature09  600 non-null    float64
 10  feature10  600 non-null    float64
 11  feature11  600 non-null    float64
 12  feature12  600 non-null    float64
 13  feature13  600 non-null    float64
 14  feature14  600 non-null    float64
 15  feature15  600 non-null    float64
 16  feature16  600 non-null    float64
 17  feature17  600 non-null    float64
 18  feature18  600 non-null    float64
 19  feature19  600 non-null    float64
 20  feature20  600 non-null    float64
 21  feature21  600 non-null    float64
 22  feature22  600 non-null    float64
 23  feature23  600 non-null    float64
 24  feature24  600 non-null    float64
 25  feature25  600 non-null    float64
 26  feature26  600 non-null    float64
 27  feature27  600 non-null    float64
 28  feature28  600 non-null    float64
 29  feature29  600 non-null    float64
 30  feature30  600 non-null    float64
 31  feature31  600 non-null    float64
 32  feature32  600 non-null    float64
 33  feature33  600 non-null    float64
 34  feature34  600 non-null    float64
 35  feature35  600 non-null    float64
 36  feature36  600 non-null    float64
 37  feature37  600 non-null    float64
 38  feature38  600 non-null    float64
 39  feature39  600 non-null    float64
 40  feature40  600 non-null    float64
 41  feature41  600 non-null    float64
 42  feature42  600 non-null    float64
 43  feature43  600 non-null    float64
 44  feature44  600 non-null    float64
 45  feature45  600 non-null    float64
 46  feature46  600 non-null    float64
 47  feature47  600 non-null    float64
 48  feature48  600 non-null    float64
 49  feature49  600 non-null    float64
 50  feature50  600 non-null    float64
 51  feature51  600 non-null    float64
 52  feature52  600 non-null    float64
 53  feature53  600 non-null    float64
 54  label      600 non-null    int64
dtypes: float64(54), int64(1)
memory usage: 257.9 KB

In [87]:
train_unlabeled_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35400 entries, 0 to 35399
Data columns (total 54 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature00  35400 non-null  float64
 1   feature01  35400 non-null  float64
 2   feature02  35400 non-null  float64
 3   feature03  35400 non-null  float64
 4   feature04  35400 non-null  float64
 5   feature05  35400 non-null  float64
 6   feature06  35400 non-null  float64
 7   feature07  35400 non-null  float64
 8   feature08  35400 non-null  float64
 9   feature09  35400 non-null  float64
 10  feature10  35400 non-null  float64
 11  feature11  35400 non-null  float64
 12  feature12  35400 non-null  float64
 13  feature13  35400 non-null  float64
 14  feature14  35400 non-null  float64
 15  feature15  35400 non-null  float64
 16  feature16  35400 non-null  float64
 17  feature17  35400 non-null  float64
 18  feature18  35400 non-null  float64
 19  feature19  35400 non-null  float64
 20  feature20  35400 non-null  float64
 21  feature21  35400 non-null  float64
 22  feature22  35400 non-null  float64
 23  feature23  35400 non-null  float64
 24  feature24  35400 non-null  float64
 25  feature25  35400 non-null  float64
 26  feature26  35400 non-null  float64
 27  feature27  35400 non-null  float64
 28  feature28  35400 non-null  float64
 29  feature29  35400 non-null  float64
 30  feature30  35400 non-null  float64
 31  feature31  35400 non-null  float64
 32  feature32  35400 non-null  float64
 33  feature33  35400 non-null  float64
 34  feature34  35400 non-null  float64
 35  feature35  35400 non-null  float64
 36  feature36  35400 non-null  float64
 37  feature37  35400 non-null  float64
 38  feature38  35400 non-null  float64
 39  feature39  35400 non-null  float64
 40  feature40  35400 non-null  float64
 41  feature41  35400 non-null  float64
 42  feature42  35400 non-null  float64
 43  feature43  35400 non-null  float64
 44  feature44  35400 non-null  float64
 45  feature45  35400 non-null  float64
 46  feature46  35400 non-null  float64
 47  feature47  35400 non-null  float64
 48  feature48  35400 non-null  float64
 49  feature49  35400 non-null  float64
 50  feature50  35400 non-null  float64
 51  feature51  35400 non-null  float64
 52  feature52  35400 non-null  float64
 53  feature53  35400 non-null  float64
dtypes: float64(54)
memory usage: 14.6 MB

In [84]:
train_labeled_df.head()

,feature00,feature01,feature02,feature03,feature04,feature05,feature06,feature07,feature08,feature09,...,feature45,feature46,feature47,feature48,feature49,feature50,feature51,feature52,feature53,label
0,0.034444,0.675000,0.125000,0.471831,0.037795,0.606010,0.103719,0.116935,0.591769,164.5050,...,0.418762,0.108996,0.030243,127.1270,0.507133,16.8630,21.29920,0.234618,0.203286,1
1,0.511788,0.908333,0.938889,0.497099,0.523966,0.796687,0.753478,0.018035,0.399890,95.4772,...,0.491379,0.309884,0.023332,104.9920,1.298300,35.8197,10.03990,0.550098,0.508312,0
2,0.036991,0.187500,0.244444,0.087196,0.631222,0.182883,0.213541,0.055069,0.192929,117.2490,...,0.725362,0.262356,0.013398,97.5426,0.983545,61.9603,22.31880,0.008264,0.355757,2
3,0.513426,1.000000,0.831250,0.437059,0.659260,0.740733,0.808800,0.013999,0.382345,180.0300,...,0.186861,0.289043,0.044456,54.2987,-3.257110,31.8470,14.27600,0.038241,0.269582,0
4,0.042564,0.393750,0.152778,0.364017,0.939443,0.336967,0.136705,0.054793,0.292448,74.8465,...,0.747113,0.347403,0.014224,114.3010,-0.228550,32.3348,8.59465,0.256730,0.034544,1

In [85]:
test_df.head()

,feature00,feature01,feature02,feature03,feature04,feature05,feature06,feature07,feature08,feature09,...,feature44,feature45,feature46,feature47,feature48,feature49,feature50,feature51,feature52,feature53
0,0.016742,0.147222,0.150000,0.564064,0.304031,0.129883,0.128273,0.063948,0.241876,142.0010,...,31.2143,0.957767,0.276386,0.060472,73.1759,0.452955,20.84030,9.47423,0.123675,0.429721
1,0.266181,0.612500,0.575000,0.324865,0.718015,0.585819,0.468718,0.021024,0.244208,94.9535,...,39.8859,0.197237,0.652344,0.059728,124.2810,-0.337859,71.86170,9.81574,0.016800,0.128224
2,0.073652,1.000000,0.533333,0.347160,0.758717,1.435560,0.433331,0.060108,0.861903,79.3390,...,19.4151,0.161392,0.322697,0.030470,48.0434,0.982209,41.41150,19.11940,0.007483,0.322325
3,0.036001,0.166667,0.280556,0.077144,0.854725,0.154132,0.242230,0.044687,0.230074,64.1879,...,26.2440,0.791264,0.207546,0.019573,146.5090,0.290709,8.46295,10.64140,0.082893,1.009750
4,0.014578,0.288889,0.089583,0.184039,0.069310,0.229095,0.075752,0.087733,0.436717,166.2400,...,23.4851,0.210290,0.311521,0.056996,40.9335,2.559280,32.61400,1.35763,0.103067,1.022440

## Extra Tree Classifier

In [43]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier

Random forest

In [44]:
X_train = train_df[['Elevation', 'Aspect', 'Slope', 'Hillshade_Morning',
                    'Hillshade_Afternoon', 'Hillshade_Evening', 'Distance_To_River',
                    'Distance_From_Road', 'Distance_From_Pollutant', 'Sector', 'Soil']]
y_train = train_df[['Plant_species']]

X_test = test_df

random_forest = RandomForestClassifier(
    n_estimators=255, criterion='entropy', warm_start=True)
random_forest.fit(X_train, y_train)

y_pred = random_forest.predict(X_test)

y_pred_df = pd.DataFrame()
y_pred_df['Id'] = np.arange(20000)
y_pred_df['Category'] = y_pred

y_pred_df.to_csv('./submission/CLF_RF_E255_CE_WS.csv', index=False)

/var/folders/ln/5crzqg4144jgkv82ryrmmdz00000gn/T/ipykernel_14853/2973403834.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train, y_train)

Extra tree classifier

In [45]:
X_train = train_df[['Elevation', 'Aspect', 'Slope', 'Hillshade_Morning',
                    'Hillshade_Afternoon', 'Hillshade_Evening', 'Distance_To_River',
                    'Distance_From_Road', 'Distance_From_Pollutant', 'Sector', 'Soil']]
y_train = train_df[['Plant_species']]

X_test = test_df

extra_tree = ExtraTreeClassifier(random_state=0)

extra_tree.fit(X_train, y_train)

y_pred = extra_tree.predict(X_test)

y_pred_df = pd.DataFrame()
y_pred_df['Id'] = np.arange(20000)
y_pred_df['Category'] = y_pred

y_pred_df.to_csv('./submission/ET.csv', index=False)

Extra tree classifier with Bagging

In [63]:
X_train = train_df[['Elevation', 'Aspect', 'Slope', 'Hillshade_Morning',
                    'Hillshade_Afternoon', 'Hillshade_Evening', 'Distance_To_River',
                    'Distance_From_Road', 'Distance_From_Pollutant', 'Sector', 'Soil']]
y_train = train_df[['Plant_species']]

X_test = test_df

extra_tree = ExtraTreeClassifier(random_state=0, criterion="entropy", splitter="best", class_weight="balanced")

model = BaggingClassifier(extra_tree, random_state=0,n_estimators=200).fit(
    X_train, y_train)

y_pred = model.predict(X_test)

y_pred_df = pd.DataFrame()
y_pred_df['Id'] = np.arange(20000)
y_pred_df['Category'] = y_pred

y_pred_df.to_csv('./submission/ET_B_Ce_Sb_CWb_NE200.csv', index=False)

/Users/kwontaekhyun/.local/lib/python3.9/site-packages/sklearn/ensemble/_bagging.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

## Self-training

In [75]:
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.feature_selection import RFECV

In [88]:
train_labeled_df.columns

Index(['feature00', 'feature01', 'feature02', 'feature03', 'feature04',
       'feature05', 'feature06', 'feature07', 'feature08', 'feature09',
       'feature10', 'feature11', 'feature12', 'feature13', 'feature14',
       'feature15', 'feature16', 'feature17', 'feature18', 'feature19',
       'feature20', 'feature21', 'feature22', 'feature23', 'feature24',
       'feature25', 'feature26', 'feature27', 'feature28', 'feature29',
       'feature30', 'feature31', 'feature32', 'feature33', 'feature34',
       'feature35', 'feature36', 'feature37', 'feature38', 'feature39',
       'feature40', 'feature41', 'feature42', 'feature43', 'feature44',
       'feature45', 'feature46', 'feature47', 'feature48', 'feature49',
       'feature50', 'feature51', 'feature52', 'feature53', 'label'],
      dtype='object')

In [89]:
dummy_train_unlabeled_df = train_unlabeled_df.copy()
dummy_train_unlabeled_df['label'] = -1

In [120]:
dummy_test_df = test_df.copy()
dummy_test_df['label'] = -1

In [129]:
data_df = pd.concat([train_labeled_df, dummy_train_unlabeled_df])

In [91]:
X_train = data_df[['feature00', 'feature01', 'feature02', 'feature03', 'feature04',
                   'feature05', 'feature06', 'feature07', 'feature08', 'feature09',
                   'feature10', 'feature11', 'feature12', 'feature13', 'feature14',
                   'feature15', 'feature16', 'feature17', 'feature18', 'feature19',
                   'feature20', 'feature21', 'feature22', 'feature23', 'feature24',
                   'feature25', 'feature26', 'feature27', 'feature28', 'feature29',
                   'feature30', 'feature31', 'feature32', 'feature33', 'feature34',
                   'feature35', 'feature36', 'feature37', 'feature38', 'feature39',
                   'feature40', 'feature41', 'feature42', 'feature43', 'feature44',
                   'feature45', 'feature46', 'feature47', 'feature48', 'feature49',
                   'feature50', 'feature51', 'feature52', 'feature53']]
y_train = data_df[['label']]

X_test = test_df

extra_tree = ExtraTreeClassifier(
    random_state=0, criterion="entropy", splitter="best", class_weight="balanced")
model = BaggingClassifier(extra_tree, random_state=0, n_estimators=200)

self_training_model = SelfTrainingClassifier(model, criterion="k_best")
self_training_model.fit(X_train, y_train)

y_pred = self_training_model.predict(X_test)

y_pred_df = pd.DataFrame()
y_pred_df['Id'] = np.arange(6000)
y_pred_df['Category'] = y_pred

y_pred_df.to_csv('./submission/ST_B_Ce_Sb_CWb_NE200_BFt_Ck.csv', index=False)

/Users/kwontaekhyun/.local/lib/python3.9/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [116]:
stat_df = data_df.describe()

In [122]:
X_train = train_labeled_df[['feature00', 'feature01', 'feature02', 'feature03', 'feature04',
                            'feature05', 'feature06', 'feature07', 'feature08', 'feature09',
                            'feature10', 'feature11', 'feature12', 'feature13', 'feature14',
                            'feature15', 'feature16', 'feature17', 'feature18', 'feature19',
                            'feature20', 'feature21', 'feature22', 'feature23', 'feature24',
                            'feature25', 'feature26', 'feature27', 'feature28', 'feature29',
                            'feature30', 'feature31', 'feature32', 'feature33', 'feature34',
                            'feature35', 'feature36', 'feature37', 'feature38', 'feature39',
                            'feature40', 'feature41', 'feature42', 'feature43', 'feature44',
                            'feature45', 'feature46', 'feature47', 'feature48', 'feature49',
                            'feature50', 'feature51', 'feature52', 'feature53']]
y_train = train_labeled_df[['label']]

X_test = test_df

extra_tree = ExtraTreeClassifier(
    random_state=0, criterion="entropy", splitter="best", class_weight="balanced")
model = BaggingClassifier(extra_tree, random_state=0, n_estimators=150)

self_training_model = SelfTrainingClassifier(model, criterion="k_best", k_best=9)

selector = RFECV(estimator=extra_tree, step=1, cv=5)
selector = selector.fit(X_train, y_train)

print(selector.support_)
print(selector.ranking_)

[False  True  True False  True False False False False False False  True
  True False  True False False False False  True  True False  True False
 False False False False False False False False False False False False
 False False  True False False  True False False False False False False
  True False False False False False]
[28  1  1 31  1  3  4  8 16 26 19  1  1 36  1 21  9 10 41  1  1 39  1 18
  7 24 12  5 22 40 23 33 11 14 15 37 17 32  1  2 38  1 25 20 30 42  6 13
  1 27 29 43 34 35]

In [126]:
column_list = ['feature00', 'feature05', 'feature06',
               'feature09', 'feature12', 'feature13', 'feature14', 'feature19', 'feature21', 'feature25']

### 아래 코드로 최종적으로 제출하였습니다.

In [132]:
X_train = data_df[['feature00', 'feature01', 'feature02', 'feature03', 'feature04',
                   'feature05', 'feature06', 'feature07', 'feature08', 'feature09',
                   'feature10', 'feature11', 'feature12', 'feature13', 'feature14',
                   'feature15', 'feature16', 'feature17', 'feature18', 'feature19',
                   'feature20', 'feature21', 'feature22', 'feature23', 'feature24',
                   'feature25', 'feature26', 'feature27', 'feature28', 'feature29',
                   'feature30', 'feature31', 'feature32', 'feature33', 'feature34',
                   'feature35', 'feature36', 'feature37', 'feature38', 'feature39',
                   'feature40', 'feature41', 'feature42', 'feature43', 'feature44',
                   'feature45', 'feature46', 'feature47', 'feature48', 'feature49',
                   'feature50', 'feature51', 'feature52', 'feature53']]
X_train = selector.transform(X_train)
y_train = data_df[['label']]

X_test = test_df

extra_tree = ExtraTreeClassifier(
    random_state=0, criterion="entropy", splitter="best", class_weight="balanced")
model = BaggingClassifier(extra_tree, random_state=0, n_estimators=150)

self_training_model = SelfTrainingClassifier(model, criterion="k_best", k_best=9)
self_training_model.fit(X_train, y_train)

y_pred = self_training_model.predict(selector.transform(X_test))

y_pred_df = pd.DataFrame()
y_pred_df['Id'] = np.arange(6000)
y_pred_df['Category'] = y_pred

y_pred_df.to_csv('./submission/ST_B_Ce_Sb_CWb_NE150_BFt_Ck_RFE_KB9.csv', index=False)

/Users/kwontaekhyun/.local/lib/python3.9/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [127]:
X_train = data_df[['feature00', 'feature01', 'feature02', 'feature03', 'feature04',
                   'feature05', 'feature06', 'feature07', 'feature08', 'feature09',
                   'feature10', 'feature11', 'feature12', 'feature13', 'feature14',
                   'feature15', 'feature16', 'feature17', 'feature18', 'feature19',
                   'feature20', 'feature21', 'feature22', 'feature23', 'feature24',
                   'feature25', 'feature26', 'feature27', 'feature28', 'feature29',
                   'feature30', 'feature31', 'feature32', 'feature33', 'feature34',
                   'feature35', 'feature36', 'feature37', 'feature38', 'feature39',
                   'feature40', 'feature41', 'feature42', 'feature43', 'feature44',
                   'feature45', 'feature46', 'feature47', 'feature48', 'feature49',
                   'feature50', 'feature51', 'feature52', 'feature53']]
X_train = X_train[column_list]
y_train = data_df[['label']]

X_test = test_df

extra_tree = ExtraTreeClassifier(
    random_state=0, criterion="entropy", splitter="best", class_weight="balanced")
model = BaggingClassifier(extra_tree, random_state=0, n_estimators=150)

self_training_model = SelfTrainingClassifier(
    model, criterion="k_best", k_best=9)
self_training_model.fit(X_train, y_train)

y_pred = self_training_model.predict(X_test[column_list])

y_pred_df = pd.DataFrame()
y_pred_df['Id'] = np.arange(6000)
y_pred_df['Category'] = y_pred

y_pred_df.to_csv(
    './submission/ST_B_Ce_Sb_CWb_NE150_BFt_Ck_RFE_KB9_CL.csv', index=False)

/Users/kwontaekhyun/.local/lib/python3.9/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [125]:
GM_df = train_labeled_df.groupby('label').mean()